#!/usr/bin/env node
/**
 * Regenerates docs/ATLAS.md straight from the live sources:
 *   - categories + planned counts from src/core/categories.ts
 *   - live algorithms scanned from src/algorithms .ts files (defineAlgorithm blocks)
 *   - canonical event types parsed from src/core/types.ts
 *
 * Usage: npm run atlas
 */
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function read(relative) {
  return readFileSync(path.join(root, relative), 'utf8');
}

function parseCategories() {
  const source = read('src/core/categories.ts');
  const blockRe =
    /\{\s*id:\s*'([^']+)',\s*name:\s*'([^']+)',\s*blurb:\s*'([^']+)',\s*atlasPages:\s*'([^']+)'\s*\}/g;
  const categories = [];
  for (const match of source.matchAll(blockRe)) {
    const [, id, name, blurb, atlasPages] = match;
    const plannedMatch = /\((\d+)\s+algorithms\)/.exec(atlasPages);
    categories.push({
      id,
      name,
      blurb,
      atlasPages,
      planned: plannedMatch ? Number(plannedMatch[1]) : 0
    });
  }
  if (categories.length === 0) {
    throw new Error('could not parse CATEGORIES from src/core/categories.ts');
  }
  return categories;
}

function parseEventTypes() {
  const source = read('src/core/types.ts');
  const start = source.indexOf('CORE_EVENT_TYPES = [');
  if (start < 0) return [];
  const end = source.indexOf('] as const', start);
  return [...source.slice(start, end).matchAll(/'([a-z-]+)'/g)].map((match) => match[1]);
}

function walk(directory, out = []) {
  for (const entry of readdirSync(directory)) {
    const full = path.join(directory, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (entry.endsWith('.ts') && !entry.endsWith('.test.ts') && entry !== 'index.ts') out.push(full);
  }
  return out;
}

function parseAlgorithms() {
  const algorithms = [];
  for (const file of walk(path.join(root, 'src/algorithms'))) {
    const source = readFileSync(file, 'utf8');
    // Anchor on the call site (`defineAlgorithm<`), never the import statement.
    let anchor = source.indexOf('defineAlgorithm<');
    if (anchor < 0) anchor = source.indexOf('defineAlgorithm(');
    if (anchor < 0) continue;
    const block = source.slice(anchor);
    const id =
      /ALGORITHM_ID\s*=\s*'([a-z0-9-]+)'/.exec(source)?.[1] ??
      /id:\s*'([a-z0-9-]+)'/.exec(block)?.[1];
    const name = /name:\s*'([^']+)'/.exec(block)?.[1];
    const category = /category:\s*'([^']+)'/.exec(block)?.[1];
    const difficulty = /difficulty:\s*'([^']+)'/.exec(block)?.[1];
    if (!id || !name || !category || !difficulty) {
      throw new Error(`could not parse the definition header in ${path.relative(root, file)}`);
    }
    algorithms.push({
      id,
      name,
      category,
      difficulty,
      file: path.relative(root, file).replace(/\\/g, '/')
    });
  }
  return algorithms;
}

function percent(part, whole) {
  return whole <= 0 ? '0%' : `${Math.round((100 * part) / whole)}%`;
}
const RULES = [
  'Schema-validated input with a per-field reason for every rejection.',
  'Executable TypeScript reference plus Python, C++ and Java listings (>20 chars each).',
  'One event per semantic transition: title, description, why, invariant, anchored code lines.',
  'Visualization derived only from event highlights/mutations — never hidden view state.',
  'Tests covering canonical, invalid, empty and singleton inputs plus a trace-property assertion.',
  'Deterministic: identical input produces an identical trace (checked in CI).',
  'Concept doc (intuition, invariants, correctness, mistakes) and complexity for all cases.',
  'Practice questions generated from the trace and graded deterministically.'
];

function markdown(categories, algorithms, eventTypes) {
  const plannedTotal = categories.reduce((sum, category) => sum + category.planned, 0);
  const lines = [
    '# AlgoViz Atlas — contract & coverage',
    '',
    '> Generated by `npm run atlas` (scripts/generate-atlas.mjs) straight from the sources.',
    '> Edit `src/core/categories.ts` or add algorithms, then re-run — do not hand-edit the tables.',
    '',
    '## Scope',
    '',
    `- ${plannedTotal} algorithms planned across ${categories.length} categories (Cinematic Atlas).`,
    `- ${algorithms.length} implemented and routable today (${percent(algorithms.length, plannedTotal)} coverage).`,
    '- The sidebar lists only *live* algorithms; planned entries stay indexed until they satisfy the definition of done.',
    '',
    '## Categories & coverage',
    '',
    '| Category | Atlas pages | Planned | Live | Coverage |',
    '| --- | --- | ---: | ---: | ---: |'
  ];
  for (const category of categories) {
    const live = algorithms.filter((algorithm) => algorithm.category === category.id).length;
    lines.push(
      `| ${category.name} | ${category.atlasPages} | ${category.planned} | ${live} | ${percent(live, category.planned)} |`
    );
  }
  lines.push(
    '',
    '## Live algorithms',
    '',
    '| Algorithm | Category | Difficulty | Source |',
    '| --- | --- | --- | --- |'
  );
  for (const algorithm of [...algorithms].sort(
    (a, b) => a.category.localeCompare(b.category) || a.name.localeCompare(b.name)
  )) {
    lines.push(
      `| ${algorithm.name} (\`${algorithm.id}\`) | ${algorithm.category} | ${algorithm.difficulty} | [\`${algorithm.file}\`](../${algorithm.file}) |`
    );
  }
  lines.push('', '## Definition of done', '');
  for (const rule of RULES) lines.push(`- ${rule}`);
  lines.push(
    '',
    '## Trace contract',
    '',
    '- Steps are 1-based and contiguous; `stateBefore` of step n equals `stateAfter` of step n-1.',
    '- Every event carries a title, description and why — generic filler words fail CI.',
    '- Code anchors resolve to unique lines of the executable TypeScript implementation.',
    '- Counters equal the sum of per-event complexity impacts; traces are JSON-serialisable.',
    '- Identical input produces an identical trace (determinism checked in CI).',
    `- Canonical event types: ${eventTypes.map((type) => `\`${type}\``).join(', ')}.`,
    '',
    '## How to add an algorithm',
    '',
    '1. `npm run scaffold -- <category> <name>` — creates a contract-complete file.',
    '2. Replace the TODO semantics; register it in `src/algorithms/index.ts`.',
    '3. `npm run verify` then `npm run atlas` to refresh this document.',
    ''
  );
  return lines.join('\n');
}

try {
  const categories = parseCategories();
  const algorithms = parseAlgorithms();
  const unknown = algorithms.filter((algorithm) => !categories.some((c) => c.id === algorithm.category));
  if (unknown.length > 0) {
    console.warn(`warning: unknown categories for: ${unknown.map((a) => a.id).join(', ')}`);
  }
  mkdirSync(path.join(root, 'docs'), { recursive: true });
  writeFileSync(
    path.join(root, 'docs/ATLAS.md'),
    markdown(categories, algorithms, parseEventTypes()),
    'utf8'
  );
  console.log(
    `wrote docs/ATLAS.md — ${algorithms.length} live algorithms, ${categories.length} categories`
  );
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}